version: "3.9"
volumes:
  db_bankwiz_volume: null
networks:
  bridge:
    driver: bridge
services:
  mysql:
    image: mysql:8.0.33
    container_name: bankwiz_mysql
    ports:
      - '8306:3306'
    volumes:
      - db_bankwiz_volume:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: BankwizRootPass2023
      MYSQL_DATABASE: bankwiz_db
      MYSQL_USER: bankwiz_user
      MYSQL_PASSWORD: BankwizPass2023
    networks:
      - bridge
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.2
    container_name: bankwiz_phpmyadmin
    ports:
      - '8180:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: BankwizRootPass2023
    networks:
      - bridge
  swaggerapi:
    image: swaggerapi/swagger-ui:v5.9.1
    container_name: swaggerapi
    ports:
      - '8280:8080'
    environment:
      SWAGGER_JSON_URL: https://raw.githubusercontent.com/jbwittner/bankwiz_openapi/main/openapi.yaml