version: "3.9"
volumes:
  db_bankwiz_volume: null
services:
  mysql:
    image: mysql:8.0.33
    container_name: bankwiz_mysql
    ports:
      - '8306:3306'
    volumes:
      - db_bankwiz_volume:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: BankwizRootPass2023
      MYSQL_DATABASE: bankwiz_db
      MYSQL_USER: bankwiz_user
      MYSQL_PASSWORD: BankwizPass2023
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:5.2
    container_name: bankwiz_phpmyadmin
    ports:
      - '8180:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: BankwizRootPass2023
  swaggereditor:
    image: swaggerapi/swagger-editor:v4-latest
    container_name: bankwiz_swaggereditor
    ports:
      - '8280:8080'
    environment:
      URL: https://raw.githubusercontent.com/jbwittner/bankwiz_server/develop/openapi.yaml