volumes:
  db_bankwiz_volume:
  pgadmin_bankwiz_volume:
services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: bankwiz_database
    ports:
      - '5432:5432'
    volumes:
      - db_bankwiz_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bankwiz_db
      POSTGRES_USER: bankwiz_user
      POSTGRES_PASSWORD: BankwizPass2023
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.4
    container_name: bankwiz_pgadmin
    ports:
      - '8180:80'
    volumes:
      - pgadmin_bankwiz_volume:/var/lib/pgadmin
      - ./pg/servers.json:/pgadmin4/servers.json
      - ./pg/pgpass:/tmp/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: user-bankwizz@bankwizz.com
      PGADMIN_DEFAULT_PASSWORD: BankwizPass2023
    entrypoint: >
      /bin/sh -c "
      mkdir -p /var/lib/pgadmin/storage/user-bankwizz_bankwizz.com;
      cp /tmp/pgpass /var/lib/pgadmin/storage/user-bankwizz_bankwizz.com/pgpass;
      chmod 600 /var/lib/pgadmin/storage/user-bankwizz_bankwizz.com/pgpass;
      /entrypoint.sh;
      "
  swaggereditor:
    image: swaggerapi/swagger-editor:v4-latest
    container_name: bankwiz_swaggereditor
    ports:
      - '8280:8080'
    environment:
      URL: https://raw.githubusercontent.com/jbwittner/bankwiz_server/develop/openapi.yaml