version: '3.9'
services:
  serverapp:
    depends_on:
      - mysql
    image: ghcr.io/jbwittner/bankwiz_server:develop-latest
    container_name: bankwiz_server_frontend
    ports:
      - '8080:8080'
    environment:
      APPLICATION_DB_HOST: mysql
      APPLICATION_DB_PORT: 3306
      APPLICATION_DB_NAME: bankwiz_db
      APPLICATION_DB_USER: bankwiz_user
      APPLICATION_DB_PASSWORD: BankwizPass2023
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      PROFILES: development
    networks:
      - bridge